# Generated by Django 4.2.1 on 2023-08-27 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, default='', max_length=10000, verbose_name='Описание проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Краткое описание проекта'),
        ),
    ]
