# Generated by Django 4.2.1 on 2023-09-28 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('project', '0002_projectnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content_type',
            field=models.ForeignKey(help_text='Специфика', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='project',
            name='object_id',
            field=models.PositiveIntegerField(null=True, verbose_name='ID специфики'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название проекта'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['content_type', 'object_id'], name='index_content_type_project'),
        ),
    ]
