# Generated by Django 4.2.1 on 2023-10-19 12:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_content_type_project_object_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoPointProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Позиция на карте')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_points', to='project.project')),
            ],
        ),
    ]
