# Generated by Django 4.2.1 on 2023-11-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_geopointproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='seo_description',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='SEO-описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='seo_keywords',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='SEO ключевые слова'),
        ),
    ]
