# Generated by Django 4.2.1 on 2023-11-07 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project_seo_description_project_seo_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.CharField(blank=True, max_length=100, verbose_name='Наименование контакта')),
                ('value', models.CharField(max_length=100, verbose_name='Значение')),
                ('contact_type', models.IntegerField(choices=[('Другое', 1), ('Телефон', 2), ('Электронная почта', 3), ('Вебсайт', 4), ('Телеграм', 5), ('Дискорд', 6)], verbose_name='Тип контакта')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='project.project')),
            ],
            options={
                'verbose_name': 'Контакт проекта',
                'verbose_name_plural': 'Контакты проекта',
            },
        ),
    ]
