# Generated by Django 4.2.1 on 2024-01-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_contactproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactproject',
            name='contact_type',
            field=models.IntegerField(choices=[(1, 'Другое'), (2, 'Телефон'), (3, 'Электронная почта'), (4, 'Вебсайт'), (5, 'Телеграм'), (6, 'Дискорд')], verbose_name='Тип контакта'),
        ),
    ]
