# Generated by Django 4.2.1 on 2023-09-28 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0003_project_content_type_project_object_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompostInputResourceDetailsSpecificity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, default='', max_length=150, verbose_name='Комментарий')),
            ],
        ),
        migrations.CreateModel(
            name='CompostInputResourceSpecificity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование ресурса')),
            ],
            options={
                'verbose_name': 'Принимаемое сырьё',
                'verbose_name_plural': 'Сырьё',
            },
        ),
        migrations.CreateModel(
            name='WebportalSpecificity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, default='', verbose_name='Ссылка на портал')),
                ('project_permanent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.project')),
            ],
            options={
                'verbose_name': 'Разработка веб-портала',
                'verbose_name_plural': 'Веб-порталы',
            },
        ),
        migrations.CreateModel(
            name='CompostSpecificity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_permanent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.project')),
                ('resources', models.ManyToManyField(related_name='composts', through='project_specificity.CompostInputResourceDetailsSpecificity', to='project_specificity.compostinputresourcespecificity')),
            ],
            options={
                'verbose_name': 'Компостирование',
                'verbose_name_plural': 'Компосты',
            },
        ),
        migrations.AddField(
            model_name='compostinputresourcedetailsspecificity',
            name='compost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_resources', to='project_specificity.compostspecificity'),
        ),
        migrations.AddField(
            model_name='compostinputresourcedetailsspecificity',
            name='input_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='project_specificity.compostinputresourcespecificity'),
        ),
    ]
