# Generated by Django 4.2.1 on 2023-10-03 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_specificity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compostinputresourcedetailsspecificity',
            name='compost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project_specificity.compostspecificity'),
        ),
        migrations.AlterField(
            model_name='compostinputresourcedetailsspecificity',
            name='input_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project_specificity.compostinputresourcespecificity'),
        ),
    ]
