# Generated by Django 4.2.1 on 2023-10-03 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_specificity', '0003_remove_compostspecificity_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compostinputresourcedetailsspecificity',
            name='compost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='project_specificity.compostspecificity'),
        ),
    ]
