# Generated by Django 4.2.1 on 2023-10-26 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_geopointproject'),
        ('project_specificity', '0005_prodcoopspecificity_consumercoopspecificity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compostspecificity',
            options={'verbose_name': 'Компостный друг | Червеферма', 'verbose_name_plural': 'Компостные друзья | Червефермы'},
        ),
        migrations.CreateModel(
            name='PeoplecampingSpecificity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_permanent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.project')),
            ],
            options={
                'verbose_name': 'Народная база отдыха',
                'verbose_name_plural': 'Народные базы отдыха',
            },
        ),
        migrations.CreateModel(
            name='EcocenterSpecificity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_permanent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.project')),
            ],
            options={
                'verbose_name': 'Экоцентр | Приём вторсырья',
                'verbose_name_plural': 'Экоцентры | Приём вторсырья',
            },
        ),
        migrations.CreateModel(
            name='CoworkingSpecificity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_permanent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.project')),
            ],
            options={
                'verbose_name': 'Открытая мастерская',
                'verbose_name_plural': 'Открытые мастерские',
            },
        ),
        migrations.CreateModel(
            name='CoopgardenSpecificity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_permanent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.project')),
            ],
            options={
                'verbose_name': 'Кооп. теплиц., огород, сад',
                'verbose_name_plural': 'Кооп. теплицы., огороды, сады',
            },
        ),
        migrations.CreateModel(
            name='CoopeaterySpecificity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_permanent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.project')),
            ],
            options={
                'verbose_name': 'Кооперативная столовая',
                'verbose_name_plural': 'Кооперативные столовые',
            },
        ),
        migrations.CreateModel(
            name='ColivingSpecificity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_permanent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.project')),
            ],
            options={
                'verbose_name': 'Коливинг',
                'verbose_name_plural': 'Коливинги',
            },
        ),
    ]
